version: '3.7'
services:
  amfi_mysql:
    image: mysql:8.0
    volumes:
      - "amfidb:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amfi
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: password

volumes:
  amfidb: